name: Generate Metrics Release

on:
  push:
    branches: [main, develop]
  release:
    types: [released]

jobs:
  send-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Criar diretório
        run: mkdir analytics-raw-data

      - name: Create Metrics SonarCloud
        run: python3 metrics/sonar-metrics.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.GIT_PERSONAL_TOKEN}}@github.com/fga-eps-mds/2024.1-SINDPOL-DOC" sindpol_docs_repo
          mkdir -p sindpol_docs_repo/analytics-raw-data
          cp -R analytics-raw-data/*.json sindpol_docs_repo/analytics-raw-data
          cd sindpol_docs_repo
          git add .
          git commit -m "Métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."
